server:
  port: 19975
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${QBOT_DB_PATH}
    username:
    password:
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 5
      validation-query: SELECT 1
      test-while-idle: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.qbot.cq.business.user.entity.po
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: strike_out
      logic-not-delete-value: 0
      logic-delete-value: 1
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
